version: 2
jobs:
  build:
    docker:
      - image: bepsays/ci-goreleaser
    filters:
        tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
    steps:
      - checkout
      - run:
          command: |
            goreleaser --skip-publish
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
