version: 2
jobs:
  build:
    docker:
      - image: bepsays/ci-goreleaser
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: goreleaser
workflows:
  version: 2
  release:
      jobs:
        - build:
            context: org-global
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
              branches:
                ignore: /.*/
