version: 2
jobs:
  build:
    docker:
      - image: bepsays/ci-goreleaser
    steps:
      - checkout
      - run:
          command: |
            goreleaser --skip-publish
workflows:
  version: 2
  build-workflow:
      jobs:
        - build:
            filters:
              tags:
                only: /v[0-9]+(\.[0-9]+)*(-.*)*/
